version: "3"
services:
    api:
        build:
            context: .
            dockerfile: ./cmd/server/Dockerfile
        environment:
            - DATABASE_URL=postgres://postgres@postgres:5432/postgres?sslmode=disable
            - PORT=8080
        ports:
            - "8080:8080"
    postgres:
        image: postgres:11.6
        ports:
            - "5439:5432"
